spring:
    datasource:  # H2 DB 설정
        url:  jdbc:h2:~/test
        driverClassName: org.h2.Driver
        username: sa
        password:
        initialization-mode: always
    h2:
        console:
            enabled: true
            path: /h2-console # H2 DB 웹콘솔 사용하도록 설정 (http://localhost:8080/h2-console)
    jpa:
        database: H2
        show-sql: true # Jpa 수행 시 SQL문 로그 출력
        properties:
            hibernate:
                format_sql: true # 쿼리 출력시 포맷 정렬되도록 설정
    jwt:
        header: Authorization
        secret: VlwEyVBsYt9V7zq57TejMnVUyzblYcfPQye08f7MGVA9XkHa
    redis:
        host: 127.0.0.1
        port: 6379
server:
    port: 8081

